name: cog_nn
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cloudpickle=3.1.1
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.13
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - farama-notifications=0.0.4
  - filelock=3.19.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gymnasium=1.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=21.1.2
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libtiff=4.7.1
  - libtorch=2.8.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=1.0
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openssl=3.5.4
  - optree=0.17.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pygments=2.19.2
  - pyparsing=3.2.5
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytorch=2.8.0
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
    - gym==0.26.2
    - neurogym==2.2.0
    - swig==4.3.1.post0
    - torchinfo==1.8.0

